version: "3.9"

services:

  store-intelligence-api:
    build: .
    container_name: store-intelligence-api

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    working_dir: /app

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    environment:
      - PYTHONUNBUFFERED=1

    restart: unless-stopped




    